language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
install:
  - pip3 install mypy types-cachetools -r requirements.txt
before_script:
  - pip3 freeze
script:
  - python3 -m unittest test

